name: Release

on: push

env:
  REGISTRY: ghcr.io
  ORG_NAME: tunjudge

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        lang:
          - name: C++ 7.3.0
            imageName: cpp
            tag: 7.3.0

          - name: C# 6.12.0
            imageName: csharp
            tag: 6.12.0

          - name: Java 8
            imageName: java
            tag: 8

          - name: Kotlin 1.4.20
            imageName: kotlin
            tag: 1.4.20

          - name: Scala 2.13.4
            imageName: scala
            tag: 2.13.4

          - name: Node 14.18.0
            imageName: node
            tag: 14.18.0

          - name: Python 2.7.18
            imageName: python
            tag: 2.7.18

          - name: Python 3.7.10
            imageName: python
            tag: 3.7.10
   
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.lang.name }} Docker image
        uses: docker/build-push-action@v2
        if: github.event.head_commit.message == matrix.lang.name
        with:
          context: ${{ matrix.lang.imageName }}/${{ matrix.lang.tag }}
          tags: ${{ env.REGISTRY }}/${{ env.ORG_NAME }}/lang/${{ matrix.lang.imageName }}:${{ matrix.lang.tag }}
          push: true
