name: Release

on: push

env:
  REGISTRY: ghcr.io
  ORG_NAME: tunjudge

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        lang:
          - name: C++ 7.3.0
            context: cpp/7.3.0
            tag: cpp:7.3.0
          - name: C# 6.12.0
            context: csharp/6.12.0.107
            tag: csharp:6.12.0.107
          - name: Java 8
            context: java/8
            tag: java:8
          - name: Kotlin 1.4.20
            context: kotlin/1.4.20
            tag: kotlin:1.4.20
          - name: Node 14.18.0
            context: node/14.18.0
            tag: node:14.18.0

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build and push ${{ matrix.lang.name }} Docker image
      #   uses: docker/build-push-action@v2
      #   if: github.event.head_commit.message == 'Release ${{ matrix.lang.name }}'
      #   with:
      #     context: ${{ matrix.lang.context }}
      #     tags: ${{ env.REGISTRY }}/${{ env.ORG_NAME }}/lang/${{ matrix.lang.tag }}
      #     push: true
      - name: Build and push ${{ matrix.lang.name }} Docker image
        if: github.event.head_commit.message == 'Release ${{ matrix.lang.name }}'
        run: |
          echo ${{ github.event.head_commit.message == 'Release ${{ matrix.lang.name }}' }}
