name: Release

on:
  push

env:
  REGISTRY: ghcr.io
  ORG_NAME: tunjudge

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lang:
          - name: C++
            context: cpp/7.3.0
            tag: cpp:7.3.0
          - name: Java
            context: java/8
            tag: java:8

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v2.1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        if: contains(steps.changed-files.outputs.modified_files, '${{ matrix.lang.context }}/Dockerfile')
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.lang.name }} Docker image
        uses: docker/build-push-action@v2
        if: contains(steps.changed-files.outputs.modified_files, '${{ matrix.lang.context }}/Dockerfile')
        with:
          context: ${{ matrix.lang.context }}
          tags: ${{ env.REGISTRY }}/${{ env.ORG_NAME }}/lang/${{ matrix.lang.tag }}
          push: true
